// import 'package:objectbox/objectbox.dart';

// @Entity()
// class TaskModel {
//   @Id(assignable: true)
//   int id;
//   String title;
//   bool isCompleted;

//   TaskModel({
//     this.id = 0, // 0 means the ID will be auto-generated by ObjectBox
//     required this.title,
//     this.isCompleted = false,
//   });
// }
